### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by jwohlfert23** [laravel-notification-channels/pusher-push-notifications#13]
<img width="573" alt="screen shot 2016-08-23 at 8 11 35 pm" src="https://cloud.githubusercontent.com/assets/2797531/17914162/d5d3eb4c-696d-11e6-888b-cb8ab5d95c3a.png">

**Comment by NassarX** [comment]
@jwohlfert23 I have the same issue !
tried to install [pusher-php-server](https://github.com/pusher/pusher-http-phpl) ^2.6 
but still get the same message every time  run 'composer require laravel-notification-channels/pusher-push-notifications'. any help ?
