### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by aaronhuisinga** [laravel-notification-channels/pusher-push-notifications#16]
Hey @themsaid,
Would you be able to get a new release tagged for this library so we can stop manually requiring an outdated version of the Pusher PHP Server library? I see you've already merged a commit updating the requirement to v2.6, but Packagist is still pulling the version requiring v2.5.0-RC4.

Thanks!

**Comment by themsaid** [comment]
1.0.2 is just tagged :)

Thank you for notifying me.

**Comment by aaronhuisinga** [comment]
Well that was fast! I was going to submit a PR for the new Pusher version, and noticed it was already committed.

Thanks so much, @themsaid!
