### ISSUE TITLE
Will it work on Android/iOS when app is closed on mobile ?

### ISSUE THREAD

**Issue by afrazahmmad** [laravel-notification-channels/pusher-push-notifications#37]
Thanks guys for great package!

I have a question!
On web-app I can send and receive notifications while web-page is active.
But In mobile, I want to get notifications even if mobile app is closed. Will it work ? Or I will have to use pusher beams for that ?

**Comment by atymic** [comment]
I think this would be a question for pusher support :)

**Comment by atymic** [comment]
Closed due to inactivity

**Comment by anish-techpro** [comment]
Push Notification is not working when app is closed.
[According to Pusher Beams](https://pusher.com/docs/beams/guides/handle-incoming-notifications#handle-all-notifications):

> When your application is in the background, this service will not be called unless there is only a data payload in the notification. The notification key cannot be used.

But there is no way to send just data using this package. The 'notification' key always goes in 'fcm'.
Is there any way i can make the push notification work in background using this package?

**Comment by shanaka-sync** [comment]
Did you find the solution ?
