### ISSUE TITLE
Push Notification is not working when app is closed (Android).

### ISSUE THREAD

**Issue by anish-techpro** [laravel-notification-channels/pusher-push-notifications#47]
Push Notification is not working when app is closed.

[According to Pusher Beams](https://pusher.com/docs/beams/guides/handle-incoming-notifications#handle-all-notifications):

> When your application is in the background, this service will not be called unless there is only a data payload in the notification. The notification key cannot be used.

But there is no way to send just data using this package. The 'notification' key always goes in 'fcm'.
Is there any way i can make the push notification work in background using this package?

**Comment by vahidzoli** [comment]
when app closed fcm notification not work, you must use fcm data for send notification.for example:

> 
> "fcm" => array(
>                     "notification" => array(
>                         "title" => "New Program",
>                         "body" => $message
>                     ),
>                     **"data" => array(
>                         "key" => $message,
>                     )**
>                 )
