### ISSUE TITLE
Support publishToUsers

### ISSUE THREAD

**Issue by xicond** [laravel-notification-channels/pusher-push-notifications#51]
please support publishToUsers, or at least dont make the beamClient protected

**Comment by AndreasElia** [comment]
I'd like to have a crack at implementing this but I'm unsure on what the usage would be like?

**Comment by AndreasElia** [comment]
This issue can now be closed.

/cc: @atymic

**Comment by andregce** [comment]
This is great, thank you so much @AndreasElia.

**Comment by AndreasElia** [comment]
My pleasure @andregce 👍

**Comment by atymic** [comment]
Yep, thanks mate :)

**Comment by andregce** [comment]
@atymic now that the PR is merged, can you guys make a new release? Would love to pull the new addition through composer.

**Comment by AndreasElia** [comment]
@atymic could this be arranged?

**Comment by schmidfelix** [comment]
Sorry for pushing, but could this be arranged? @atymic

**Comment by atymic** [comment]
https://github.com/laravel-notification-channels/pusher-push-notifications/releases/tag/2.3.1
