### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/pusher-push-notifications#54]
Laravel 8 has been released today and we need to update this repo to support it.
See https://laravel.com/docs/8.x/upgrade & https://github.com/laravel-notification-channels/channels/issues/107

**Comment by atymic** [comment]
Closed in #55

**Comment by goranculibrk** [comment]
@atymic may I ask how did you install the package in Laravel 8? I'm getting the error for `guzzle 6` version, due to the `pusher/pusher-push-notification`

**Comment by atymic** [comment]
Looks like it's blocked by this PR:
https://github.com/pusher/push-notifications-php/pull/30/files

**Comment by jonathanlloyd** [comment]
> Looks like it's blocked by this PR:
> https://github.com/pusher/push-notifications-php/pull/30/files

Merged. Will release asap.
