### ISSUE TITLE
production.ERROR: Driver [NotificationChannels\PusherPushNotifications\PusherChannel] not supported.

### ISSUE THREAD

**Issue by wecojo** [laravel-notification-channels/pusher-push-notifications#56]
Hi, 
I installed this package, it worked well on my local machine.

But after i deployed it to my server online and tried executing it.

It displays this error:

`production.ERROR: Driver [NotificationChannels\PusherPushNotifications\PusherChannel] not supported.  {"userId":20,"exception":"[object] (InvalidArgumentException(code: 0): Driver [NotificationChannels\\PusherPushNotifications\\PusherChannel] not supported. at */public_html/vendor/laravel/framework/src/Illuminate/Support/Manager.php:119)`

Please help

**Comment by wecojo** [comment]
Sorry, i didn't install it properly.

**Comment by Satish-Acharya** [comment]
@wecojo I still have the same issue on laravel 8, its works well in local wamp  but no on production linux server.. I have tried to reinstall the complete vendor folder. But still the same.. Any suggestions.

**Comment by wecojo** [comment]
> @wecojo I still have the same issue on laravel 8, its works well in local wamp  but no on production linux server.. I have tried to reinstall the complete vendor folder. But still the same.. Any suggestions.

Am sorry, i didn't how i solve it.

My issue was that after i installed on my local server, i think i may have deleted it's file name from composer.json by mistake.

So all i did was reinstalled, this time made sure it's file name appeared in conposer.json

**Comment by Satish-Acharya** [comment]
> > @wecojo I still have the same issue on laravel 8, its works well in local wamp  but no on production linux server.. I have tried to reinstall the complete vendor folder. But still the same.. Any suggestions.
> 
> Am sorry, i didn't display how i solve it.
> 
> My issue was that after i installed it on my local server, i think i may have deleted it's file name from composer.json by mistake.
> 
> So all i did was reinstall it, this time making sure it's file name appeared in composer.json

I have fixed that, actually i didn't restart the queue daemon, i.e., supervisorctl after pushing my code. I assumed that, laravel would take it up. Then after doing some trail and error it did work.. So we need to restart supervisor/supervisorctl after new notifications created.
