### ISSUE TITLE
How can i send a Notification to a specific User

### ISSUE THREAD

**Issue by julianlaibach** [laravel-notification-channels/pusher-push-notifications#71]
I´m wondering how i can send Notifications to a specific User. The Auth Process is completely working and if i send a Notification from the Debug Console in the Pusher Backend it is also working but if i do the following:

`Notification::send(User::all(), new ExampleNotification);`

and the ExampleNotification looks like this:

```
<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;
use NotificationChannels\PusherPushNotifications\PusherChannel;
use NotificationChannels\PusherPushNotifications\PusherMessage;

class ExampleNotification extends Notification
{
    use Queueable;

    /**
     * Get the notification's delivery channels.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return [PusherChannel::class];
    }

    
    public function toPushNotification($notifiable)
    {
        return PusherMessage::create()
            ->web()
            ->title("Test")
            ->body("Test");
    }

}
```

I do not receive a Notification on the registered Device and in the Pusher Debug Console it says Notification triggered to Users with Devices: 0 and Users: 0.

What exactly am i doing wrong?

**Comment by julianlaibach** [comment]
For anyone experiencing the same behaviour i had to adjust the User Model and add the following lines:

```
public $pushNotificationType = 'users';

public function routeNotificationFor($channel)
{
    if($channel === 'PusherPushNotifications'){
        return $this->id;
    }

    $class = str_replace('\\', '.', get_class($this));

    return $class.'.'.$this->getKey();
}
```

Now the User ID(s) passed when calling:

`Notification::send(User::all(), new ExampleNotification);`

are the Targets and the Notifications being displayed succesfully

**Comment by XinnieSol** [comment]
I still don't get the notifications after trying this out
